### PR TITLE
fix(venv_bundler): install all deps as not editable

### LINKED ISSUE #37: bundle dependencies marked as editable
For dependencies marked as editable, this plugin will create .pth files including the local location of the path-based dependency. In that sense, the dependency is not bundled.

Is there a reason for a bundled install to observe the "develop = true" flag?  If so, can we have an option to install these packages as non-editable instead?  According to my reading of https://github.com/python-poetry/poetry/issues/1382#issuecomment-1266291854, this bundler is supposed to handle that installation case.

poetry               1.2.1    
poetry-core          1.2.0
poetry-plugin-bundle 1.1.0

### PR DESCRIPTION
**Pull request by vladkolotvin**
fixes #37

### CODE REVIEW

**Comment by vladkolotvin** [comment]
pre-commit.ci autofix

**Comment by radoering** [comment]
Looks straight forward. 😄

Can you add a test please?

**Comment by vladkolotvin** [comment]
pre-commit.ci autofix

**Comment by vladkolotvin** [comment]
@radoering done

**Comment by vladkolotvin** [comment]
@radoering @branchvincent 
ping

**Comment by vladkolotvin** [comment]
@radoering could you ship a new release?

**Comment by radoering** [comment]
I will try to prepare one within the next days.

**Pull request merged**
